/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#32353d",
        "on-secondary-container": "#a8afff",
        "outline-variant": "#424655",
        "secondary-container": "#343d96",
        "on-primary-container": "#002661",
        "background": "#10131b",
        "surface-container": "#1d1f27",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#341100",
        "secondary": "#bdc2ff",
        "surface-container-high": "#272a32",
        "surface-bright": "#363942",
        "tertiary-fixed-dim": "#ffb692",
        "primary-container": "#558dff",
        "surface-dim": "#10131b",
        "on-secondary": "#1b247f",
        "outline": "#8c90a0",
        "secondary-fixed": "#e0e0ff",
        "error": "#ffb4ab",
        "on-primary": "#002d6e",
        "on-primary-fixed-variant": "#00429b",
        "surface-variant": "#32353d",
        "surface": "#10131b",
        "primary-fixed-dim": "#b0c6ff",
        "tertiary": "#ffb692",
        "secondary-fixed-dim": "#bdc2ff",
        "on-tertiary": "#562000",
        "on-primary-fixed": "#001945",
        "tertiary-fixed": "#ffdbcb",
        "on-surface-variant": "#c2c6d7",
        "inverse-on-surface": "#2d3039",
        "primary-fixed": "#d9e2ff",
        "inverse-primary": "#0058ca",
        "on-tertiary-fixed-variant": "#793000",
        "on-surface": "#e1e2ed",
        "on-background": "#e1e2ed",
        "tertiary-container": "#eb6a19",
        "on-secondary-fixed-variant": "#343d96",
        "surface-tint": "#b0c6ff",
        "surface-container-low": "#191b23",
        "on-error": "#690005",
        "on-secondary-fixed": "#000767",
        "inverse-surface": "#e1e2ed",
        "surface-container-lowest": "#0b0e16",
        "error-container": "#93000a",
        "primary": "#b0c6ff",
        "on-tertiary-container": "#4b1b00",
        border: "#424655", // Adding default Shadcn aliases
        input: "#32353d",
        ring: "#b0c6ff",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "unit": "8px",
        "stack-md": "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "margin-desktop": "40px",
        "stack-sm": "8px",
        "stack-lg": "48px"
      },
      fontFamily: {
        "display-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg-mobile": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["13px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
